name: copy rules

on:
  push:
    branches:
      - main
    schedule:
      - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Checkout Rules
      uses: actions/checkout@v2
      with:
        repository: Loyalsoldier/surge-rules
        ref: release
        path: Rules
    - name: copy proxy
      run: cp -r Rules/ruleset/proxy.txt proxy.list
    - name: Upload to this repo
      run: |
        if [ -n "$(git status -s)" ];then
            echo "规则同步"
            git config --global user.name "Ewha"
            git config --global user.email "royyanxin@gmail.com" 
            git add . 
            git commit -m '+'  
            git push -u origin main
            echo "完成同步"
        else
            echo "规则未修改"
        fi
        exit 0
